"""Encoding tests — golden vectors produced with viem 2.x.

Every vector here was generated by the reference viem stack (the same one
openclawnch ships) and proves the pure-Python encoders are byte-for-byte
compatible with it. If any of these break, redemption calldata would diverge
from what the on-chain DelegationManager expects.
"""

from __future__ import annotations

import pytest
from eth_account import Account
from eth_account.messages import encode_typed_data
from eth_utils import keccak

from clawmes.delegation import encoding as E
from clawmes.delegation.types import ROOT_AUTHORITY, Caveat, SignedDelegation, UnsignedDelegation

# The canonical fixture used across vectors.
_DELEGATE = "0x2222222222222222222222222222222222222222"
_DELEGATOR = "0x3333333333333333333333333333333333333333"
_ENFORCER = "0x92Bf12322527cAA612fd31a0e810472BBB106A8F"
_TERMS = "0x" + "00" * 31 + "64"


def _signed(sig: str = "0x" + "aa" * 65) -> SignedDelegation:
    return SignedDelegation(
        delegate=_DELEGATE,
        delegator=_DELEGATOR,
        authority=ROOT_AUTHORITY,
        caveats=(Caveat(enforcer=_ENFORCER, terms=_TERMS, args="0x"),),
        salt=42,
        signature=sig,
    )


class TestSelectors:
    def test_redeem(self):
        assert E.SEL_REDEEM == "0xcef6d209"

    def test_disable(self):
        assert E.SEL_DISABLE == "0x49934047"

    def test_get_hash(self):
        assert E.SEL_GET_HASH == "0x66134607"

    def test_disabled(self):
        assert E.SEL_DISABLED == "0x2d40d052"

    def test_selector_helper(self):
        assert E.selector("disabledDelegations(bytes32)") == "0x2d40d052"


class TestTermsEncoders:
    def test_value_lte(self):
        assert E.terms_value_lte(100) == "0x" + (100).to_bytes(32, "big").hex()

    def test_native_transfer_amount(self):
        assert E.terms_native_transfer_amount(5) == "0x" + (5).to_bytes(32, "big").hex()

    def test_native_period_golden(self):
        assert E.terms_native_period(5 * 10**18, 0, 86400) == (
            "0x0000000000000000000000000000000000000000000000004563918244f40000"
            "0000000000000000000000000000000000000000000000000000000000000000"
            "0000000000000000000000000000000000000000000000000000000000015180"
        )

    def test_erc20_transfer_amount_golden_packed_52_bytes(self):
        terms = E.terms_erc20_transfer_amount(
            "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", 100_000_000
        )
        assert terms == (
            "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
            "0000000000000000000000000000000000000000000000000000000005f5e100"
        )
        # 52 bytes = address (20) + uint256 (32).
        assert len(bytes.fromhex(terms[2:])) == 52

    def test_erc20_period(self):
        terms = E.terms_erc20_period("0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", 100, 0, 86400)
        # 4 * 32-byte words.
        assert len(bytes.fromhex(terms[2:])) == 128

    def test_limited_calls(self):
        assert E.terms_limited_calls(10) == "0x" + (10).to_bytes(32, "big").hex()

    def test_timestamp_golden(self):
        assert E.terms_timestamp(0, 1750000000) == (
            "0x0000000000000000000000000000000000000000000000000000000000000000"
            "00000000000000000000000000000000000000000000000000000000684ee180"
        )

    def test_allowed_targets_golden(self):
        terms = E.terms_allowed_targets(
            [
                "0x1111111111111111111111111111111111111111",
                "0x2222222222222222222222222222222222222222",
            ]
        )
        assert terms == (
            "0x0000000000000000000000000000000000000000000000000000000000000020"
            "0000000000000000000000000000000000000000000000000000000000000002"
            "0000000000000000000000001111111111111111111111111111111111111111"
            "0000000000000000000000002222222222222222222222222222222222222222"
        )


class TestExecution:
    def test_encode_execution_golden(self):
        exec_hex = E.encode_execution(
            "0x1111111111111111111111111111111111111111",
            10**18,
            "0xa9059cbb" + "22" * 32,
        )
        assert exec_hex == (
            "0x1111111111111111111111111111111111111111"
            "0000000000000000000000000000000000000000000000000de0b6b3a7640000"
            "a9059cbb2222222222222222222222222222222222222222222222222222222222222222"
        )

    def test_encode_execution_empty_calldata(self):
        exec_hex = E.encode_execution("0x" + "11" * 20, 0, "0x")
        assert exec_hex == "0x" + "11" * 20 + "00" * 32


class TestPermissionContext:
    def test_single_delegation_hash_matches_viem(self):
        ctx = E.encode_permission_context([_signed()])
        digest = "0x" + keccak(bytes.fromhex(ctx[2:])).hex()
        assert digest == "0x75f3547d84b86f20a3a4acd32b142d547970b830d871f9e47c66b8d47147e2d0"

    def test_chain_reversed_for_multi(self):
        # A two-element chain is reversed to leaf-first; encoding a reversed
        # input by hand must match encoding the forward chain.
        a = _signed("0x" + "aa" * 65)
        b = SignedDelegation(
            delegate="0x4444444444444444444444444444444444444444",
            delegator=_DELEGATE,
            authority="0x" + "cd" * 32,
            caveats=(),
            salt=7,
            signature="0x" + "bb" * 65,
        )
        forward = E.encode_permission_context([a, b])
        manual_reversed = E.encode_permission_context([b])  # not equal; sanity
        assert forward != manual_reversed
        # Reversing [a, b] → [b, a]; encoding [b, a] as two singles won't match,
        # but the leaf (b) must appear first in the forward encoding.
        assert b.delegator[2:].lower() in forward[2:].lower()


class TestCalldata:
    def test_redeem_calldata_hash_matches_viem(self):
        ctx = E.encode_permission_context([_signed()])
        execution = E.encode_execution(
            "0x1111111111111111111111111111111111111111", 10**18, "0xa9059cbb" + "22" * 32
        )
        calldata = E.build_redeem_calldata(ctx, execution, "0x" + "00" * 32)
        digest = "0x" + keccak(bytes.fromhex(calldata[2:])).hex()
        assert digest == "0x385a6ae3600c50fc0e12dd21b303029b1c4d67d0a3ee40d2e9a867aab2547ab6"

    def test_disable_calldata_prefix(self):
        assert E.build_disable_calldata(_signed()).startswith("0x49934047")

    def test_get_hash_calldata_prefix(self):
        assert E.build_get_hash_calldata(_signed()).startswith("0x66134607")

    def test_disabled_calldata(self):
        data = E.build_disabled_calldata("0x" + "ab" * 32)
        assert data == "0x2d40d052" + "ab" * 32


class TestTypedDataAndSignatureParity:
    def test_signature_matches_viem_exactly(self):
        unsigned = UnsignedDelegation(
            delegate=_DELEGATE,
            delegator=_DELEGATOR,
            authority=ROOT_AUTHORITY,
            caveats=(Caveat(enforcer=_ENFORCER, terms=_TERMS),),
            salt=42,
        )
        typed = E.build_typed_data(unsigned, 8453)
        acct = Account.from_key("0x" + "11" * 32)
        sig = acct.sign_message(encode_typed_data(full_message=typed)).signature.hex()
        sig = sig if sig.startswith("0x") else "0x" + sig
        assert sig == (
            "0xd07fe5c701389696bb8fb1400d880b92f33a8cda7a1ac15c5fa1032e2f73a8f1"
            "46e529af367fde801788dcad8a0bae6920fa4a8a2a65ba24d9ae9f28d3980a201b"
        )

    def test_typed_data_excludes_args_from_caveat(self):
        typed = E.build_typed_data(_signed(), 8453)
        assert typed["types"]["Caveat"] == [
            {"name": "enforcer", "type": "address"},
            {"name": "terms", "type": "bytes"},
        ]
        # message caveats carry no args
        assert set(typed["message"]["caveats"][0]) == {"enforcer", "terms"}

    def test_typed_data_domain(self):
        typed = E.build_typed_data(_signed(), 1)
        assert typed["domain"]["chainId"] == 1
        assert typed["domain"]["name"] == "DelegationManager"


class TestErc20OpEncoders:
    def test_transfer(self):
        assert E.encode_erc20_transfer("0x" + "11" * 20, 5) == (
            "0xa9059cbb" + "00" * 12 + "11" * 20 + (5).to_bytes(32, "big").hex()
        )

    def test_approve(self):
        assert E.encode_erc20_approve("0x" + "22" * 20, 0) == (
            "0x095ea7b3" + "00" * 12 + "22" * 20 + "00" * 32
        )

    def test_erc721_transfer_from(self):
        data = E.encode_erc721_transfer_from("0x" + "11" * 20, "0x" + "22" * 20, 7)
        assert data.startswith("0x23b872dd")
        assert data.endswith((7).to_bytes(32, "big").hex())


class TestHelpers:
    def test_bad_address_raises(self):
        with pytest.raises(ValueError, match="20-byte address"):
            E.encode_execution("0x1234", 0, "0x")

    def test_empty_hex_bytes(self):
        # "0x" and "" both decode to empty bytes (exercised via execution).
        assert E.encode_execution("0x" + "00" * 20, 0, "") == "0x" + "00" * 20 + "00" * 32
